from .fastapi import (
    AuthenticationASGIMiddleware,
    AuthorizationDependencyError,
    install_auth_exception_handlers,
    install_auth_middleware,
    principal_from_request,
    require_platform_roles,
    require_tenant_roles,
)
from .permissions import (
    AuthorizationAuditSink,
    AuthorizationDeniedAuditRecord,
    PermissionDenied,
    has_platform_role,
    require_platform_role,
    require_role,
    require_tenant_role,
)
from .resolution import (
    AppUserRecord,
    IdentityRepository,
    IdentityResolutionError,
    PrincipalResolver,
    TenantMembershipRecord,
)
from .tokens import (
    AuthenticationError,
    AuthMode,
    AuthSettings,
    DevTokenValidator,
    JwksTokenValidator,
    Principal,
    TestTokenValidator,
    TokenValidator,
    bearer_token,
)

__all__ = [
    "AuthMode",
    "AuthSettings",
    "AuthenticationError",
    "AuthenticationASGIMiddleware",
    "AppUserRecord",
    "AuthorizationAuditSink",
    "AuthorizationDependencyError",
    "AuthorizationDeniedAuditRecord",
    "DevTokenValidator",
    "IdentityRepository",
    "IdentityResolutionError",
    "JwksTokenValidator",
    "PermissionDenied",
    "Principal",
    "PrincipalResolver",
    "TenantMembershipRecord",
    "TestTokenValidator",
    "TokenValidator",
    "bearer_token",
    "has_platform_role",
    "install_auth_exception_handlers",
    "install_auth_middleware",
    "principal_from_request",
    "require_platform_role",
    "require_platform_roles",
    "require_role",
    "require_tenant_role",
    "require_tenant_roles",
]
