name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  repository-checks:
    name: Repository checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        run: make setup

      - name: Test
        run: make test

      - name: Lint
        run: make lint
